name: Deploy to Google Cloud Storage
on: [push]

jobs:
  deploy:
    name: Deploy
    runs-on: ubuntu-latest
    steps:
      - name: Checkout the repository
        uses: actions/checkout@v1

      - name: Setup node.js 12
        uses: actions/setup-node@v1
        with:
          node-version: 12.x

      - name: Install npm dependencies and build the app
        run: |
          npm install
          npm run build --if-present

      - name: Authenticated with Google Cloud
        uses: actions/gcloud/auth@master
        env:
          GCLOUD_AUTH: ${{ secrets.GCLOUD_AUTH }}

      - name: Remove all current files
        uses: vsoch/gcloud-actions/gsutil@add/gsutil
        with:
          args: -m rm gs://www.brunosabot.com/**

      - name: Copy new files with cache control header
        uses: vsoch/gcloud-actions/gsutil@add/gsutil
        with:
          args: -m -h "Cache-Control:public,max-age=31536000" cp -a public-read -r build/* gs://www.brunosabot.com

      - name: Copy new index.html file
        uses: vsoch/gcloud-actions/gsutil@add/gsutil
        with:
          args: cp -a public-read build/index.html gs://www.brunosabot.com
